import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/sections/Header";

export const metadata: Metadata = {
  title: "Morrocan SaaS Ai",
  description: "Generated by Morrocan SaaS Ai",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
